### ISSUE TITLE
Unable to set theme to other than `default`

### ISSUE THREAD

**Issue by aaulia** [tomoyukim/vscode-mermaid-editor#39] opened 2021-04-10 19:28 UTC
Hello,

It seems that I'm unable to set the theme to other than `default` from the mermaid config json.

```
- config.json
{
    "theme": "dark"
}
```

```
- mmd
sequenceDiagram
    %% @config{./config.json}
    %% @backgroundColor{black}
    .
    .
    .
```

The background is black, but the diagram is still using the `default` theme. The generated SVG also still uses the `default` theme.

**Comment by tomoyukim** [comment] 2021-04-11 01:45
Thank you for your report!
I couldn't reproduce it but could you try to check the place in which your config file is put once again? It must be the same directory as your mmd file when you describe `./config.json`

**Comment by aaulia** [comment] 2021-04-11 03:56
![image](https://user-images.githubusercontent.com/161797/114291756-0eeaed00-9ab4-11eb-89c8-67de0fe5337f.png)

As you can see from the screenshot, both files are on the same directory. But the preview still show the `default` theme. FWIW I also have few other extension for markdown and a couple other for mermaid (Markdown Preview Mermaid Support and Mermaid Markdown Syntax Highlighting) but AFAIK those shouldn't interfere with this extension's preview.

**Comment by tomoyukim** [comment] 2021-04-11 05:02
Thank you for quick response. Um, does the situation continue even when you edit `.mmd` file? I'm asking it because mermaid-editor only refresh the diagram when `.mmd` file is updated.
Or did you find any other operation to get out from the symptom?

**Comment by aaulia** [comment] 2021-04-11 05:47
The one I showed in the screenshot is something that I freshly made to demonstrate the issue. So since I start writing the mermaid file, it never uses the `dark` theme, ever. It's always use the `default` theme, despite the fact that I already set the theme to `dark` in the `config.json`.

**Comment by aaulia** [comment] 2021-04-11 05:48
I also found this [comment](https://github.com/tomoyukim/vscode-mermaid-editor/issues/31#issuecomment-752632025) from another, closed, issue. Maybe it's related.

**Comment by robcresswell** [comment] 2021-04-16 08:59
I seem to be having the same issue. It doesn't actually bother me because I used `"default"` any way, but let me know if there's anything you'd like me to help with or test to fix it

**Comment by Pindar777** [comment] 2021-04-18 15:59
@tomoyukim I just found your VSC package and like it very much.
I'd like to add to the conversation that change the background and the config-file just works via global settings. The "magic comments" instead have no effect at all.

**Comment by tomoyukim** [comment] 2021-04-24 13:46
Thank you for your patience and help. I found an error parsing attributes in the document with CRLF. It was fixed in v 0.11.0 and please check it out!

**Closed by tomoyukim** 2021-04-24 13:46 UTC
Labels: bug

**Comment by Pindar777** [comment] 2021-04-24 15:14
@tomoyukim Thank you. Works like a charm.

**Comment by robcresswell** [comment] 2021-04-28 12:01
@tomoyukim I'm not sure this is fixed. My setup is something like this:

```
.
├── .vscode
│   └── settings.json
└── src
    ├── config.json
    └── diagrams
```

`diagrams` is a directory with `.mmd` files, but its not really relevant here I think.

The `settings.json` looks like this:

```
{
  "mermaid-editor.preview.defaultMermaidConfig": "./src/config.json"
}
```

Even rendering a very trivial diagram such as 

```
sequenceDiagram
  A ->>+ B: Foo
  B ->>- A: Bar
```

results in 

![Screenshot 2021-04-28 at 13 00 07](https://user-images.githubusercontent.com/3816327/116400189-aa54bf80-a821-11eb-82b4-60a3eb1c37c9.png)
