### ISSUE TITLE
Node shape is misaligned and larger than the text

### ISSUE THREAD

**Issue by wijloc** [tomoyukim/vscode-mermaid-editor#36] opened 2021-03-26 13:24 UTC
I'm using v0.10.0 version of VSCode extension.

When I try to create a graph the node shapes is misaligned how this image can demonstrate:
![image](https://user-images.githubusercontent.com/16838209/112637872-5ec38600-8e1d-11eb-9041-c5f74af65781.png)

The size of the node shape is larger than necessary too.

I'm using default settings, Linux Ubuntu 20.04 and VSCode 1.54.3

**Comment by tomoyukim** [comment] 2021-03-28 14:07
Thank you for your report but I couldn't reproduce it. If this is caused by old mermaid.js, it may be fixed on mermaid-editor 0.10.1 including mermaid.js 8.9.2. Please check it out.

**Comment by wijloc** [comment] 2021-03-29 14:22
I installed only the VSCode Extension: tomoyukim.vscode-mermaid-editor. Do I need to install anything else?

**Comment by jostid** [comment] 2021-03-29 20:42
Same kind of problem here. The text is offset and does not fit very well. The same behavior can be seen in the preview as in an exported image: here a sample png
![mermaids](https://user-images.githubusercontent.com/79133398/112897513-01ab2700-90e0-11eb-8325-83deb60b5838.png)

**Comment by tomoyukim** [comment] 2021-04-11 01:29
> Do I need to install anything else?

@wijloc No, mermaid-editor doesn't have any external dependency.

What about executing `Mermaid:Reset Zoom` or closing/opening preview window? Is the situation improved?

**Comment by wijloc** [comment] 2021-04-12 13:00
> What about executing `Mermaid:Reset Zoom` or closing/opening preview window? Is the situation improved?
The error still happening. Reset or any command of Mermaid does not makes difference

**Comment by Pindar777** [comment] 2021-05-12 08:14
@tomoyukim The bug is also present on my windows 10 setup and the current version of your package. The very same mermaid code works just fine in the live editor. I did not use any mermaid zoom options. The erroneous diagram is save as SVG as well.

**Comment by Pindar777** [comment] 2021-06-13 10:23
@tomoyukim Seems to be working now for me.

**Comment by tomoyukim** [comment] 2021-07-03 02:17
@Pindar777 Thank you for your report! I'm not sure why it becomes fine but I guess it's caused by WebView itself.

**Comment by tomoyukim** [comment] 2021-07-03 02:17
I'm sorry to be my late reply. But if you find the same trouble, please open a new issue.

**Closed by tomoyukim** 2021-07-03 02:17 UTC
Labels: bug
