### ISSUE TITLE
Could not generate images from .mmd files including non-ascii characters.

### ISSUE THREAD

**Issue by ndac-todoroki** [tomoyukim/vscode-mermaid-editor#27] opened 2020-12-10 17:11 UTC
An example mermaid file:
```mmd
sequenceDiagram
    participant x as Aさん
    participant y as Bさん

    x ->> y: プレゼントを渡す
```

The preview works: 
![image](https://user-images.githubusercontent.com/11530165/101805280-eaa6f000-3b55-11eb-81c5-24aa0c969b37.png)

But not the generator:

```
Parse error on line 1:
#mermaid-16076197498
^
Expecting 'NEWLINE', 'SPACE', 'GRAPH', got 'BRKT'

============================
```

Changing all Japanese words to ascii letters makes the generator work properly.

**Comment by tomoyukim** [comment] 2020-12-20 09:07
Thank you for reporting the bug. This seems to be caused by same reason as #29.

**Comment by tomoyukim** [comment] 2020-12-24 10:59
Thank you for waiting. This should be resolved in v0.9.0.

**Closed by tomoyukim** 2020-12-24 10:59 UTC
Labels: bug
