### ISSUE TITLE
Live preview is not live if %%{init.....} is used

### ISSUE THREAD

**Issue by brantpeery** [tomoyukim/vscode-mermaid-editor#35] opened 2021-03-26 08:49 UTC
It appears that the live previewer chokes on the %%{.  I think it is not considering it a comment line because the curly bracket is touching the %%.
This stops the previewer from updating. 
The preview does work with that syntax though. I just have to close the preview and re-open to get updates.

**Comment by tomoyukim** [comment] 2021-03-28 13:48
Thank you for reporting it! I could reproduce it and seems to be a bug of mermaid.js parser. I've raised a bug report there. I also found you can avoid the error with inserting space between `%%` and `{` like `%% {`. Please prevent the occurrence of the error using it temporarily for now. Sorry to your inconvenient.

**Comment by NeilCuzon** [comment] 2021-05-01 00:54
The syntax is that of a [directive](https://mermaid-js.github.io/mermaid/#/directives), which is  method of changing the config. 
I would refrain from using "%%"+"{}", since they might break the diagram. 

Example below changes theme to dark: 
%%{init: { "theme": "dark" }}%%
classDiagram
    Animal <|-- Duck
    Animal <|-- Fish
    Animal <|-- Zebra
    Animal : +int age
    Animal : +String gender
    Animal: +isMammal()
    Animal: +mate()
    class Duck{
      +String beakColor
      +swim()
      +quack()
    }
    class Fish{
      -int sizeInFeet
      -canEat()
    }
    class Zebra{
      +bool is_wild
      +run()
    }

**Comment by NeilCuzon** [comment] 2021-05-02 08:26
I have added this to the documentation and will be more visible to users. thanks for the contribution, with that I will close this issue. 

https://github.com/mermaid-js/mermaid/blob/master/docs/n00b-syntaxReference.md#diagram-breaking

**Comment by tomoyukim** [comment] 2021-05-05 12:45
Thank you for your information and support. I'll change my attribute syntax to avoid conflict with the directive in mermaid.js just in case.

**Comment by tomoyukim** [comment] 2021-12-24 14:57
I introduced a new attribute syntax with parenthesis like `@config()` and deprecated the old syntax in v 0.12.0. I'll remove the old one in the near future.

**Closed by tomoyukim** 2021-12-24 14:57 UTC
Labels: bug, enhancement
